name: Build image on commit to master

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/applicationset
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.16.2"
      - uses: actions/checkout@master
        with:
          path: src/applicationset

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      # Build the image
      - run: |
          docker images -a --format "{{.ID}}" | xargs -I {} docker rmi {}
          make image
        working-directory: ./src/applicationset
        env:
          CONTAINER_REGISTRY: quay.io
          IMAGE_NAMESPACE: argoproj
          IMAGE_TAG: latest
          IMAGE_PLATFORMS: linux/amd64,linux/arm64

      # Publish the image
      - run: |
          docker login quay.io --username $USERNAME --password $PASSWORD
          docker push quay.io/argoproj/argocd-applicationset:latest
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.TOKEN }}
